/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiClientDataErrorResponse from '../model/ApiClientDataErrorResponse';
import ApiForbiddenErrorResponse from '../model/ApiForbiddenErrorResponse';
import ApiLimitErrorResponse from '../model/ApiLimitErrorResponse';
import ApiNotFoundErrorResponse from '../model/ApiNotFoundErrorResponse';
import ApiServerErrorResponse from '../model/ApiServerErrorResponse';
import ApiUnauthorizedErrorResponse from '../model/ApiUnauthorizedErrorResponse';
import GetRegionWithChildrenResponse from '../model/GetRegionWithChildrenResponse';
import GetRegionsCodesResponse from '../model/GetRegionsCodesResponse';
import GetRegionsResponse from '../model/GetRegionsResponse';

/**
* Regions service.
* @module api/RegionsApi
* @version LATEST
*/
export default class RegionsApi {

    /**
    * Constructs a new RegionsApi. 
    * @alias module:api/RegionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getRegionsCodes operation.
     * @callback module:api/RegionsApi~getRegionsCodesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetRegionsCodesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Список допустимых кодов стран
     * {% include notitle [access](../../_auto/method_scopes/getRegionsCodes.md) %}  Возвращает список стран с их кодами в формате ISO 3166-1 alpha-2.  Страна производства `countryCode` понадобится при продаже товаров из-за рубежа для бизнеса. [Инструкция](../../step-by-step/business-info.md)  |**⚙️ Лимит:** 100 запросов в час| |-| 
     * @param {module:api/RegionsApi~getRegionsCodesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetRegionsCodesResponse}
     */
    getRegionsCodes(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey', 'OAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetRegionsCodesResponse;
      return this.apiClient.callApi(
        '/regions/countries', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchRegionChildren operation.
     * @callback module:api/RegionsApi~searchRegionChildrenCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetRegionWithChildrenResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Информация о дочерних регионах
     * {% include notitle [access](../../_auto/method_scopes/searchRegionChildren.md) %}  Возвращает информацию о регионах, являющихся дочерними по отношению к региону, идентификатор которого указан в запросе.  Для методов `GET regions`, `GET regions/{regionId}` и `GET regions/{regionId}/children` действует групповое ресурсное ограничение. Ограничение вводится на суммарное количество регионов, информация о которых запрошена при помощи этих методов (не более 100 000 регионов).  Объем запросов к ресурсу, который возможно выполнить в течение суток, зависит от суммарного количества регионов.  |**⚙️ Лимит:** 50 000 запросов в час| |-| 
     * @param {Number} regionId Идентификатор региона.  Идентификатор региона можно получить c помощью запроса [GET regions](../../reference/regions/searchRegionsByName.md). 
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 1)] {% note warning \"Если в методе есть `page_token`\" %}  Используйте его вместо параметра `page`.  [Подробнее о типах пагинации и их использовании](../../concepts/pagination.md)  {% endnote %}  Номер страницы результатов.  Используется вместе с параметром `page_size`.  `page_number` игнорируется, если задан `page_token` или `limit`. 
     * @param {Number} [pageSize] Размер страницы.  Используется вместе с параметром `page_number`.  `page_size` игнорируется, если задан `page_token` или `limit`. 
     * @param {module:api/RegionsApi~searchRegionChildrenCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetRegionWithChildrenResponse}
     */
    searchRegionChildren(regionId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'regionId' is set
      if (regionId === undefined || regionId === null) {
        throw new Error("Missing the required parameter 'regionId' when calling searchRegionChildren");
      }

      let pathParams = {
        'regionId': regionId
      };
      let queryParams = {
        'page': opts['page'],
        'pageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey', 'OAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetRegionWithChildrenResponse;
      return this.apiClient.callApi(
        '/regions/{regionId}/children', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchRegionsById operation.
     * @callback module:api/RegionsApi~searchRegionsByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetRegionsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Информация о регионе
     * {% include notitle [access](../../_auto/method_scopes/searchRegionsById.md) %}  Возвращает информацию о регионе.  Для методов `GET regions`, `GET regions/{regionId}` и `GET regions/{regionId}/children` действует групповое ресурсное ограничение. Ограничение вводится на суммарное количество регионов, информация о которых запрошена при помощи этих методов (не более 100 000 регионов).  Объем запросов к ресурсу, который возможно выполнить в течение суток, зависит от суммарного количества регионов.  |**⚙️ Лимит:** 50 000 запросов в час| |-| 
     * @param {Number} regionId Идентификатор региона.  Идентификатор региона можно получить c помощью запроса [GET regions](../../reference/regions/searchRegionsByName.md). 
     * @param {module:api/RegionsApi~searchRegionsByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetRegionsResponse}
     */
    searchRegionsById(regionId, callback) {
      let postBody = null;
      // verify the required parameter 'regionId' is set
      if (regionId === undefined || regionId === null) {
        throw new Error("Missing the required parameter 'regionId' when calling searchRegionsById");
      }

      let pathParams = {
        'regionId': regionId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey', 'OAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetRegionsResponse;
      return this.apiClient.callApi(
        '/regions/{regionId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchRegionsByName operation.
     * @callback module:api/RegionsApi~searchRegionsByNameCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetRegionsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Поиск регионов по их имени
     * {% include notitle [access](../../_auto/method_scopes/searchRegionsByName.md) %}  Возвращает информацию о регионе, удовлетворяющем заданным в запросе условиям поиска.  Если найдено несколько регионов, удовлетворяющих условиям поиска, возвращается информация по каждому найденному региону (но не более десяти регионов) для возможности определения нужного региона по родительским регионам.  Для методов `GET regions`, `GET regions/{regionId}` и `GET regions/{regionId}/children` действует групповое ресурсное ограничение. Ограничение вводится на суммарное количество регионов, информация о которых запрошена при помощи этих методов (не более 100 000 регионов).  Объем запросов к ресурсу, который возможно выполнить в течение суток, зависит от суммарного количества регионов.  |**⚙️ Лимит:** 50 000 запросов в час| |-| 
     * @param {String} name Название региона.  Важно учитывать регистр: первая буква должна быть заглавной, остальные — строчными. Например, `Москва`. 
     * @param {Object} opts Optional parameters
     * @param {String} [pageToken] Идентификатор страницы c результатами.  Если параметр не указан, возвращается первая страница.  Рекомендуется передавать значение выходного параметра `nextPageToken`, полученное при последнем запросе.  Если задан `page_token` и в запросе есть параметры `page_number` и `page_size`, они игнорируются. 
     * @param {Number} [limit] Количество значений на одной странице. 
     * @param {module:api/RegionsApi~searchRegionsByNameCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetRegionsResponse}
     */
    searchRegionsByName(name, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling searchRegionsByName");
      }

      let pathParams = {
      };
      let queryParams = {
        'name': name,
        'page_token': opts['pageToken'],
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKey', 'OAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetRegionsResponse;
      return this.apiClient.callApi(
        '/regions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
