/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BenefitType.
* @enum {}
* @readonly
*/
export default class BenefitType {
    
        /**
         * value: "BESTS"
         * @const
         */
        "BESTS" = "BESTS";

    
        /**
         * value: "SPLIT_0_0_4"
         * @const
         */
        "SPLIT_0_0_4" = "SPLIT_0_0_4";

    
        /**
         * value: "SPLIT_0_0_6"
         * @const
         */
        "SPLIT_0_0_6" = "SPLIT_0_0_6";

    
        /**
         * value: "SPLIT_0_0_12"
         * @const
         */
        "SPLIT_0_0_12" = "SPLIT_0_0_12";

    
        /**
         * value: "MARKET_SUBSIDY_1_4"
         * @const
         */
        "MARKET_SUBSIDY_1_4" = "MARKET_SUBSIDY_1_4";

    
        /**
         * value: "MARKET_SUBSIDY_5_9"
         * @const
         */
        "MARKET_SUBSIDY_5_9" = "MARKET_SUBSIDY_5_9";

    
        /**
         * value: "MARKET_SUBSIDY_10"
         * @const
         */
        "MARKET_SUBSIDY_10" = "MARKET_SUBSIDY_10";

    

    /**
    * Returns a <code>BenefitType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/BenefitType} The enum <code>BenefitType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

