/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CurrencyType from './CurrencyType';

/**
 * The CurrencyValueDTO model module.
 * @module model/CurrencyValueDTO
 * @version LATEST
 */
class CurrencyValueDTO {
    /**
     * Constructs a new <code>CurrencyValueDTO</code>.
     * Значение с валютой.
     * @alias module:model/CurrencyValueDTO
     * @param value {Number} Значение.
     * @param currencyId {module:model/CurrencyType} 
     */
    constructor(value, currencyId) { 
        
        CurrencyValueDTO.initialize(this, value, currencyId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, value, currencyId) { 
        obj['value'] = value;
        obj['currencyId'] = currencyId;
    }

    /**
     * Constructs a <code>CurrencyValueDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CurrencyValueDTO} obj Optional instance to populate.
     * @return {module:model/CurrencyValueDTO} The populated <code>CurrencyValueDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CurrencyValueDTO();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
            if (data.hasOwnProperty('currencyId')) {
                obj['currencyId'] = CurrencyType.constructFromObject(data['currencyId']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CurrencyValueDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CurrencyValueDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CurrencyValueDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

CurrencyValueDTO.RequiredProperties = ["value", "currencyId"];

/**
 * Значение.
 * @member {Number} value
 */
CurrencyValueDTO.prototype['value'] = undefined;

/**
 * @member {module:model/CurrencyType} currencyId
 */
CurrencyValueDTO.prototype['currencyId'] = undefined;






export default CurrencyValueDTO;

