/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReturnShipmentStatusType from './ReturnShipmentStatusType';
import ReturnType from './ReturnType';

/**
 * The GenerateUnitedReturnsRequest model module.
 * @module model/GenerateUnitedReturnsRequest
 * @version LATEST
 */
class GenerateUnitedReturnsRequest {
    /**
     * Constructs a new <code>GenerateUnitedReturnsRequest</code>.
     * Данные, необходимые для генерации отчета. 
     * @alias module:model/GenerateUnitedReturnsRequest
     * @param businessId {Number} Идентификатор кабинета.
     * @param dateFrom {Date} Начало периода, включительно.
     * @param dateTo {Date} Конец периода, включительно.
     */
    constructor(businessId, dateFrom, dateTo) { 
        
        GenerateUnitedReturnsRequest.initialize(this, businessId, dateFrom, dateTo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, businessId, dateFrom, dateTo) { 
        obj['businessId'] = businessId;
        obj['dateFrom'] = dateFrom;
        obj['dateTo'] = dateTo;
    }

    /**
     * Constructs a <code>GenerateUnitedReturnsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GenerateUnitedReturnsRequest} obj Optional instance to populate.
     * @return {module:model/GenerateUnitedReturnsRequest} The populated <code>GenerateUnitedReturnsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GenerateUnitedReturnsRequest();

            if (data.hasOwnProperty('businessId')) {
                obj['businessId'] = ApiClient.convertToType(data['businessId'], 'Number');
            }
            if (data.hasOwnProperty('dateFrom')) {
                obj['dateFrom'] = ApiClient.convertToType(data['dateFrom'], 'Date');
            }
            if (data.hasOwnProperty('dateTo')) {
                obj['dateTo'] = ApiClient.convertToType(data['dateTo'], 'Date');
            }
            if (data.hasOwnProperty('campaignIds')) {
                obj['campaignIds'] = ApiClient.convertToType(data['campaignIds'], ['Number']);
            }
            if (data.hasOwnProperty('returnType')) {
                obj['returnType'] = ReturnType.constructFromObject(data['returnType']);
            }
            if (data.hasOwnProperty('returnStatusTypes')) {
                obj['returnStatusTypes'] = ApiClient.convertToType(data['returnStatusTypes'], [ReturnShipmentStatusType]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GenerateUnitedReturnsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GenerateUnitedReturnsRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GenerateUnitedReturnsRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['campaignIds'])) {
            throw new Error("Expected the field `campaignIds` to be an array in the JSON data but got " + data['campaignIds']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['returnStatusTypes'])) {
            throw new Error("Expected the field `returnStatusTypes` to be an array in the JSON data but got " + data['returnStatusTypes']);
        }

        return true;
    }


}

GenerateUnitedReturnsRequest.RequiredProperties = ["businessId", "dateFrom", "dateTo"];

/**
 * Идентификатор кабинета.
 * @member {Number} businessId
 */
GenerateUnitedReturnsRequest.prototype['businessId'] = undefined;

/**
 * Начало периода, включительно.
 * @member {Date} dateFrom
 */
GenerateUnitedReturnsRequest.prototype['dateFrom'] = undefined;

/**
 * Конец периода, включительно.
 * @member {Date} dateTo
 */
GenerateUnitedReturnsRequest.prototype['dateTo'] = undefined;

/**
 * Список магазинов, которые нужны в отчете.
 * @member {Array.<Number>} campaignIds
 */
GenerateUnitedReturnsRequest.prototype['campaignIds'] = undefined;

/**
 * @member {module:model/ReturnType} returnType
 */
GenerateUnitedReturnsRequest.prototype['returnType'] = undefined;

/**
 * Статусы передачи возвратов, которые нужны в отчете.  Если их не указать, вернется информация по всем возвратам. 
 * @member {Array.<module:model/ReturnShipmentStatusType>} returnStatusTypes
 */
GenerateUnitedReturnsRequest.prototype['returnStatusTypes'] = undefined;






export default GenerateUnitedReturnsRequest;

