/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetGoodsFeedbackCommentsRequest model module.
 * @module model/GetGoodsFeedbackCommentsRequest
 * @version LATEST
 */
class GetGoodsFeedbackCommentsRequest {
    /**
     * Constructs a new <code>GetGoodsFeedbackCommentsRequest</code>.
     * Фильтр запроса комментариев отзыва. 
     * @alias module:model/GetGoodsFeedbackCommentsRequest
     */
    constructor() { 
        
        GetGoodsFeedbackCommentsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetGoodsFeedbackCommentsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetGoodsFeedbackCommentsRequest} obj Optional instance to populate.
     * @return {module:model/GetGoodsFeedbackCommentsRequest} The populated <code>GetGoodsFeedbackCommentsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetGoodsFeedbackCommentsRequest();

            if (data.hasOwnProperty('feedbackId')) {
                obj['feedbackId'] = ApiClient.convertToType(data['feedbackId'], 'Number');
            }
            if (data.hasOwnProperty('commentIds')) {
                obj['commentIds'] = ApiClient.convertToType(data['commentIds'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetGoodsFeedbackCommentsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetGoodsFeedbackCommentsRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['commentIds'])) {
            throw new Error("Expected the field `commentIds` to be an array in the JSON data but got " + data['commentIds']);
        }

        return true;
    }


}



/**
 * Идентификатор отзыва. 
 * @member {Number} feedbackId
 */
GetGoodsFeedbackCommentsRequest.prototype['feedbackId'] = undefined;

/**
 * Идентификаторы комментариев.  ⚠️ Не используйте это поле одновременно с другими фильтрами. Если вы хотите воспользоваться ими, оставьте поле пустым. 
 * @member {Array.<Number>} commentIds
 */
GetGoodsFeedbackCommentsRequest.prototype['commentIds'] = undefined;






export default GetGoodsFeedbackCommentsRequest;

