/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LabelsSortingType.
* @enum {}
* @readonly
*/
export default class LabelsSortingType {
    
        /**
         * value: "SORT_BY_GIVEN_ORDER"
         * @const
         */
        "SORT_BY_GIVEN_ORDER" = "SORT_BY_GIVEN_ORDER";

    
        /**
         * value: "SORT_BY_ORDER_CREATED_AT"
         * @const
         */
        "SORT_BY_ORDER_CREATED_AT" = "SORT_BY_ORDER_CREATED_AT";

    

    /**
    * Returns a <code>LabelsSortingType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LabelsSortingType} The enum <code>LabelsSortingType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

