/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OfferCardContentStatusType.
* @enum {}
* @readonly
*/
export default class OfferCardContentStatusType {
    
        /**
         * value: "UPDATING"
         * @const
         */
        "UPDATING" = "UPDATING";

    
        /**
         * value: "ACTUAL"
         * @const
         */
        "ACTUAL" = "ACTUAL";

    

    /**
    * Returns a <code>OfferCardContentStatusType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OfferCardContentStatusType} The enum <code>OfferCardContentStatusType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

