/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MediaFileUploadStateType from './MediaFileUploadStateType';

/**
 * The OfferMediaFileDTO model module.
 * @module model/OfferMediaFileDTO
 * @version LATEST
 */
class OfferMediaFileDTO {
    /**
     * Constructs a new <code>OfferMediaFileDTO</code>.
     * Информация о медиафайле товара. 
     * @alias module:model/OfferMediaFileDTO
     */
    constructor() { 
        
        OfferMediaFileDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OfferMediaFileDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OfferMediaFileDTO} obj Optional instance to populate.
     * @return {module:model/OfferMediaFileDTO} The populated <code>OfferMediaFileDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OfferMediaFileDTO();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('uploadState')) {
                obj['uploadState'] = MediaFileUploadStateType.constructFromObject(data['uploadState']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OfferMediaFileDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OfferMediaFileDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}



/**
 * Ссылка на медиафайл. 
 * @member {String} url
 */
OfferMediaFileDTO.prototype['url'] = undefined;

/**
 * Название медиафайла. 
 * @member {String} title
 */
OfferMediaFileDTO.prototype['title'] = undefined;

/**
 * @member {module:model/MediaFileUploadStateType} uploadState
 */
OfferMediaFileDTO.prototype['uploadState'] = undefined;






export default OfferMediaFileDTO;

