/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrdersStatsSubsidyOperationType from './OrdersStatsSubsidyOperationType';
import OrdersStatsSubsidyType from './OrdersStatsSubsidyType';

/**
 * The OrdersStatsSubsidyDTO model module.
 * @module model/OrdersStatsSubsidyDTO
 * @version LATEST
 */
class OrdersStatsSubsidyDTO {
    /**
     * Constructs a new <code>OrdersStatsSubsidyDTO</code>.
     * Информация о начислении баллов, которые используются для уменьшения стоимости размещения, и их списании в случае невыкупа или возврата.
     * @alias module:model/OrdersStatsSubsidyDTO
     * @param operationType {module:model/OrdersStatsSubsidyOperationType} 
     * @param type {module:model/OrdersStatsSubsidyType} 
     * @param amount {Number} Количество баллов, которые используются для уменьшения стоимости размещения, с точностью до двух знаков после запятой. 
     */
    constructor(operationType, type, amount) { 
        
        OrdersStatsSubsidyDTO.initialize(this, operationType, type, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operationType, type, amount) { 
        obj['operationType'] = operationType;
        obj['type'] = type;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>OrdersStatsSubsidyDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrdersStatsSubsidyDTO} obj Optional instance to populate.
     * @return {module:model/OrdersStatsSubsidyDTO} The populated <code>OrdersStatsSubsidyDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrdersStatsSubsidyDTO();

            if (data.hasOwnProperty('operationType')) {
                obj['operationType'] = OrdersStatsSubsidyOperationType.constructFromObject(data['operationType']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = OrdersStatsSubsidyType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrdersStatsSubsidyDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrdersStatsSubsidyDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OrdersStatsSubsidyDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

OrdersStatsSubsidyDTO.RequiredProperties = ["operationType", "type", "amount"];

/**
 * @member {module:model/OrdersStatsSubsidyOperationType} operationType
 */
OrdersStatsSubsidyDTO.prototype['operationType'] = undefined;

/**
 * @member {module:model/OrdersStatsSubsidyType} type
 */
OrdersStatsSubsidyDTO.prototype['type'] = undefined;

/**
 * Количество баллов, которые используются для уменьшения стоимости размещения, с точностью до двух знаков после запятой. 
 * @member {Number} amount
 */
OrdersStatsSubsidyDTO.prototype['amount'] = undefined;






export default OrdersStatsSubsidyDTO;

