/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ParcelBoxRequestDTO model module.
 * @module model/ParcelBoxRequestDTO
 * @version LATEST
 */
class ParcelBoxRequestDTO {
    /**
     * Constructs a new <code>ParcelBoxRequestDTO</code>.
     * Параметр отображает одно грузовое место. Вложенные поля больше не используются, передавайте параметр пустым.
     * @alias module:model/ParcelBoxRequestDTO
     */
    constructor() { 
        
        ParcelBoxRequestDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ParcelBoxRequestDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParcelBoxRequestDTO} obj Optional instance to populate.
     * @return {module:model/ParcelBoxRequestDTO} The populated <code>ParcelBoxRequestDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParcelBoxRequestDTO();

            if (data.hasOwnProperty('fulfilmentId')) {
                obj['fulfilmentId'] = ApiClient.convertToType(data['fulfilmentId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ParcelBoxRequestDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ParcelBoxRequestDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['fulfilmentId'] && !(typeof data['fulfilmentId'] === 'string' || data['fulfilmentId'] instanceof String)) {
            throw new Error("Expected the field `fulfilmentId` to be a primitive type in the JSON string but got " + data['fulfilmentId']);
        }

        return true;
    }


}



/**
 * {% note warning \"Этот параметр устарел\" %}  Не используйте его.  {% endnote %} 
 * @member {String} fulfilmentId
 */
ParcelBoxRequestDTO.prototype['fulfilmentId'] = undefined;






export default ParcelBoxRequestDTO;

