/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReportLanguageType model module.
 * @module model/ReportLanguageType
 * @version LATEST
 */
class ReportLanguageType {
    /**
     * Constructs a new <code>ReportLanguageType</code>.
     * Язык отчета:  * &#x60;RU&#x60; — русский язык. * &#x60;EN&#x60; — английский язык. 
     * @alias module:model/ReportLanguageType
     */
    constructor() { 
        
        ReportLanguageType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportLanguageType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportLanguageType} obj Optional instance to populate.
     * @return {module:model/ReportLanguageType} The populated <code>ReportLanguageType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportLanguageType();

        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReportLanguageType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReportLanguageType</code>.
     */
    static validateJSON(data) {

        return true;
    }


}








export default ReportLanguageType;

