/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ReturnDecisionSubreasonType.
* @enum {}
* @readonly
*/
export default class ReturnDecisionSubreasonType {
    
        /**
         * value: "USER_DID_NOT_LIKE"
         * @const
         */
        "USER_DID_NOT_LIKE" = "USER_DID_NOT_LIKE";

    
        /**
         * value: "USER_CHANGED_MIND"
         * @const
         */
        "USER_CHANGED_MIND" = "USER_CHANGED_MIND";

    
        /**
         * value: "DELIVERED_TOO_LONG"
         * @const
         */
        "DELIVERED_TOO_LONG" = "DELIVERED_TOO_LONG";

    
        /**
         * value: "BAD_PACKAGE"
         * @const
         */
        "BAD_PACKAGE" = "BAD_PACKAGE";

    
        /**
         * value: "DAMAGED"
         * @const
         */
        "DAMAGED" = "DAMAGED";

    
        /**
         * value: "NOT_WORKING"
         * @const
         */
        "NOT_WORKING" = "NOT_WORKING";

    
        /**
         * value: "INCOMPLETENESS"
         * @const
         */
        "INCOMPLETENESS" = "INCOMPLETENESS";

    
        /**
         * value: "WRONG_ITEM"
         * @const
         */
        "WRONG_ITEM" = "WRONG_ITEM";

    
        /**
         * value: "WRONG_COLOR"
         * @const
         */
        "WRONG_COLOR" = "WRONG_COLOR";

    
        /**
         * value: "DID_NOT_MATCH_DESCRIPTION"
         * @const
         */
        "DID_NOT_MATCH_DESCRIPTION" = "DID_NOT_MATCH_DESCRIPTION";

    
        /**
         * value: "WRONG_ORDER"
         * @const
         */
        "WRONG_ORDER" = "WRONG_ORDER";

    
        /**
         * value: "WRONG_AMOUNT_DELIVERED"
         * @const
         */
        "WRONG_AMOUNT_DELIVERED" = "WRONG_AMOUNT_DELIVERED";

    
        /**
         * value: "WRAPPING_DAMAGED"
         * @const
         */
        "WRAPPING_DAMAGED" = "WRAPPING_DAMAGED";

    
        /**
         * value: "ITEM_WAS_USED"
         * @const
         */
        "ITEM_WAS_USED" = "ITEM_WAS_USED";

    
        /**
         * value: "BROKEN"
         * @const
         */
        "BROKEN" = "BROKEN";

    
        /**
         * value: "BAD_FLOWERS"
         * @const
         */
        "BAD_FLOWERS" = "BAD_FLOWERS";

    
        /**
         * value: "PARCEL_MISSING"
         * @const
         */
        "PARCEL_MISSING" = "PARCEL_MISSING";

    
        /**
         * value: "INCOMPLETE"
         * @const
         */
        "INCOMPLETE" = "INCOMPLETE";

    
        /**
         * value: "UNKNOWN"
         * @const
         */
        "UNKNOWN" = "UNKNOWN";

    

    /**
    * Returns a <code>ReturnDecisionSubreasonType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ReturnDecisionSubreasonType} The enum <code>ReturnDecisionSubreasonType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

