/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SignatureDTO model module.
 * @module model/SignatureDTO
 * @version LATEST
 */
class SignatureDTO {
    /**
     * Constructs a new <code>SignatureDTO</code>.
     * Информация о подписи акта приема-передачи.
     * @alias module:model/SignatureDTO
     * @param signed {Boolean} Подписан ли акт приема-передачи.
     */
    constructor(signed) { 
        
        SignatureDTO.initialize(this, signed);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, signed) { 
        obj['signed'] = signed;
    }

    /**
     * Constructs a <code>SignatureDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SignatureDTO} obj Optional instance to populate.
     * @return {module:model/SignatureDTO} The populated <code>SignatureDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SignatureDTO();

            if (data.hasOwnProperty('signed')) {
                obj['signed'] = ApiClient.convertToType(data['signed'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SignatureDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SignatureDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SignatureDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SignatureDTO.RequiredProperties = ["signed"];

/**
 * Подписан ли акт приема-передачи.
 * @member {Boolean} signed
 */
SignatureDTO.prototype['signed'] = undefined;






export default SignatureDTO;

