/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CurrencyType from './CurrencyType';
import TariffParameterDTO from './TariffParameterDTO';
import TariffType from './TariffType';

/**
 * The TariffDTO model module.
 * @module model/TariffDTO
 * @version LATEST
 */
class TariffDTO {
    /**
     * Constructs a new <code>TariffDTO</code>.
     * Информация о тарифах, по которым нужно заплатить за услуги Маркета.
     * @alias module:model/TariffDTO
     * @param type {module:model/TariffType} 
     * @param amount {Number} Значение тарифа.
     * @param currency {module:model/CurrencyType} 
     * @param parameters {Array.<module:model/TariffParameterDTO>} Параметры расчета тарифа.
     */
    constructor(type, amount, currency, parameters) { 
        
        TariffDTO.initialize(this, type, amount, currency, parameters);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, amount, currency, parameters) { 
        obj['type'] = type;
        obj['amount'] = amount;
        obj['currency'] = currency;
        obj['parameters'] = parameters;
    }

    /**
     * Constructs a <code>TariffDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TariffDTO} obj Optional instance to populate.
     * @return {module:model/TariffDTO} The populated <code>TariffDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TariffDTO();

            if (data.hasOwnProperty('type')) {
                obj['type'] = TariffType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('percent')) {
                obj['percent'] = ApiClient.convertToType(data['percent'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = CurrencyType.constructFromObject(data['currency']);
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], [TariffParameterDTO]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TariffDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TariffDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TariffDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['parameters']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['parameters'])) {
                throw new Error("Expected the field `parameters` to be an array in the JSON data but got " + data['parameters']);
            }
            // validate the optional field `parameters` (array)
            for (const item of data['parameters']) {
                TariffParameterDTO.validateJSON(item);
            };
        }

        return true;
    }


}

TariffDTO.RequiredProperties = ["type", "amount", "currency", "parameters"];

/**
 * @member {module:model/TariffType} type
 */
TariffDTO.prototype['type'] = undefined;

/**
 * {% note warning \"Этот параметр устарел\" %}  Не используйте его.  {% endnote %}  Значение тарифа в процентах. 
 * @member {Number} percent
 */
TariffDTO.prototype['percent'] = undefined;

/**
 * Значение тарифа.
 * @member {Number} amount
 */
TariffDTO.prototype['amount'] = undefined;

/**
 * @member {module:model/CurrencyType} currency
 */
TariffDTO.prototype['currency'] = undefined;

/**
 * Параметры расчета тарифа.
 * @member {Array.<module:model/TariffParameterDTO>} parameters
 */
TariffDTO.prototype['parameters'] = undefined;






export default TariffDTO;

