/**
 * Партнерский API Маркета
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 
 *
 * The version of the OpenAPI document: LATEST
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WarehouseStatusType from './WarehouseStatusType';

/**
 * The WarehouseStatusDTO model module.
 * @module model/WarehouseStatusDTO
 * @version LATEST
 */
class WarehouseStatusDTO {
    /**
     * Constructs a new <code>WarehouseStatusDTO</code>.
     * Информация о статусе склада.
     * @alias module:model/WarehouseStatusDTO
     * @param status {module:model/WarehouseStatusType} 
     */
    constructor(status) { 
        
        WarehouseStatusDTO.initialize(this, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status) { 
        obj['status'] = status;
    }

    /**
     * Constructs a <code>WarehouseStatusDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WarehouseStatusDTO} obj Optional instance to populate.
     * @return {module:model/WarehouseStatusDTO} The populated <code>WarehouseStatusDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WarehouseStatusDTO();

            if (data.hasOwnProperty('status')) {
                obj['status'] = WarehouseStatusType.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WarehouseStatusDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WarehouseStatusDTO</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WarehouseStatusDTO.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

WarehouseStatusDTO.RequiredProperties = ["status"];

/**
 * @member {module:model/WarehouseStatusType} status
 */
WarehouseStatusDTO.prototype['status'] = undefined;






export default WarehouseStatusDTO;

